"""initial schema

Revision ID: d9e556c55835
Revises: 
Create Date: 2026-02-08 13:55:01.675456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e556c55835'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_key'), 'environments', ['key'], unique=True)
    op.create_table('flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('default_variant', sa.String(length=100), nullable=False),
    sa.Column('rollout_percentage', sa.Float(), nullable=True),
    sa.Column('targeted_allow', sa.Text(), nullable=False),
    sa.Column('targeted_deny', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_key'), 'flags', ['key'], unique=True)
    op.create_table('flag_environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flag_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Float(), nullable=True),
    sa.Column('targeted_allow', sa.Text(), nullable=False),
    sa.Column('targeted_deny', sa.Text(), nullable=False),
    sa.Column('default_variant', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_id', 'environment_id', name='uq_flag_env')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flag_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_id', 'environment_id', 'priority', name='uq_rule_priority')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_table('flag_environments')
    op.drop_index(op.f('ix_flags_key'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_environments_key'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
